/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto.venta.tabla;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author agus_
 */
public class TablaVentas extends javax.swing.JPanel implements KeyListener {

    /**
     * Creates new form TablaVentas
     */
    public TablaVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTabla = new javax.swing.JTable();

        jScrollPane1.setBorder(null);

        txtTabla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTabla.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Pruieba Producto", "10", "10", "10", "10"}
            },
            new String [] {
                "Código de barras ", "Descripción del Producto", "Precio Venta", "Cant", "Importe", "Existencia"
            }
        ));
        txtTabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        txtTabla.setAutoscrolls(false);
        txtTabla.setColumnSelectionAllowed(true);
        txtTabla.setDropMode(javax.swing.DropMode.ON);
        txtTabla.setGridColor(new java.awt.Color(255, 255, 255));
        txtTabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        txtTabla.setShowHorizontalLines(false);
        txtTabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTablaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTablaKeyPressed

        try{
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                int row = txtTabla.getSelectedRow();
                int column = txtTabla.getSelectedColumn();
                double preci = Double.parseDouble(txtTabla.getValueAt(row, 2) + "");
                if (column == 3) {// por cantidad
                    String can = (String) txtTabla.getValueAt(row, column);
                    double canti = Double.parseDouble(can);
                    double totalImporte = canti * preci;
                    txtTabla.setValueAt(totalImporte + "", row, 4);
                }

                if (column == 4) {// por importe
                    String imp = (String) txtTabla.getValueAt(row, column);
                    double impor = Double.parseDouble(imp);
                    double totalCanti = impor / preci;
                    txtTabla.setValueAt(totalCanti + "", row, 3);

                }
                actualizarImporteTabla();

            }

            if (evt.getKeyCode() == 107) {
                sumarDeUno();
            }

            if (evt.getKeyCode() == 109) {
                restarDeUno();
            }
            if(evt.getKeyCode() == 127){
                eliminaCelda(1);
            }
        }catch(NumberFormatException exc){
            Utilidades.confirma(confir, "Haz ingresado una letra u otro caracter en lugar de un número. Por favor revisa los datos ingresados");
        }

        if (txtTabla.getSelectedRow() >= 0) {
        }else{
            e.requestFocus();
        }
    }//GEN-LAST:event_txtTablaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable txtTabla;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
       
    }

    @Override
    public void keyPressed(KeyEvent e) {
      
    }

    @Override
    public void keyReleased(KeyEvent e) {
        
    }
}
